use clap::{App, Arg};

pub fn build() -> App<'static, 'static> {
    App::new("safe-rm")
        .version(crate_version!())
        .author(crate_authors!())
        .about("Safe Rm\nSend files to the graveyard (/tmp/graveyard-$USER by default) instead of unlinking them.")
        .arg(Arg::with_name("TARGET")
            .help("File or directory to remove")
            .multiple(true)
            .index(1))
        .arg(Arg::with_name("graveyard")
            .help("Directory where deleted files go to rest")
            .long("graveyard")
            .short("g")
            .takes_value(true))
        .arg(Arg::with_name("decompose")
            .help("Permanently deletes (unlink) the entire graveyard")
            .short("d")
            .long("decompose"))
        .arg(Arg::with_name("seance")
            .help("Prints files that were sent under the current directory")
            .short("s")
            .long("seance"))
        .arg(Arg::with_name("unbury")
            .help("Undo the last removal by the current user, or specify some file(s) in the \
                   graveyard.  Combine with -s to restore everything printed by -s.")
            .short("u")
            .long("unbury")
            .value_name("target")
            .min_values(0))
        .arg(Arg::with_name("inspect")
            .help("Prints some info about TARGET before prompting for action")
            .short("i")
            .long("inspect"))
}